### ISSUE TITLE
Difficult Time Getting Started

### ISSUE THREAD

**Issue by romanator** [sparkfun/Edison_OLED_Block#1]
Regarding the Edison_OLED_Block, there is insufficient information to get started.  If someone could provide a quick tutorial or link regarding the use of the files submitted, that would be helpful.

**Comment by ToniCorinne** [comment]
Check out our [hookup guide](https://learn.sparkfun.com/tutorials/sparkfun-blocks-for-intel-edison---oled-block-) for this block. You can also see all the other Edison tutorials we have available [here](https://learn.sparkfun.com/tutorials/tags/edison). Hope that helps!
